version: "3"
services:
  db:
    container_name: db
    image: mysql:5.7 
    restart: always
    environment:
      MYSQL_USER: admdimdim
      MYSQL_PASSWORD: admdimdim
      MYSQL_DATABASE: out_stock
      MYSQL_ROOT_PASSWORD: admdimdim
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    container_name: outstock
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: out_stock
      DB_USER: admdimdim
      DB_PASSWORD: admdimdim
    depends_on:
      - db

volumes:
  db_data:
